<?php
/**
 * Copyright (c) 2017 TechDivision GmbH
 * All rights reserved
 *
 * This product includes proprietary software developed at TechDivision GmbH, Germany
 * For more information see http://www.techdivision.com/
 *
 * To obtain a valid license for using this software please contact us at
 * license@techdivision.com
 */

/**
 * @category   Hallhuber
 * @package    Custom
 * @subpackage view
 * @copyright  Copyright (c) 2017 TechDivision GmbH (http://www.techdivision.com)
 * @version    ${release.version}
 * @link       http://www.techdivision.com/
 * @author     Martin.Eisenführer <m.eisenfuehrer@techdivision.com>
 */

/** @var $block \TechDivision\IndexSuspender\Block\Indexer */
$count = $block->countSuspender();
?>

<?php if ($count > 0): ?>
    <button onclick="setLocation('<?php /* @escapeNotVerified */ echo $block->getCleanSuspenderUrl() ?>')" type="button">
        <?php /* @escapeNotVerified */ echo  __('%1 reindex suspender (last one from %2)', $count, $block->getLastSuspender()); ?>
    </button>
<?php endif ?>